vim.keymap.set("n", "<C-e>", ":Neotree filesystem reveal left toggle<CR>")
vim.keymap.set("n", "<leader>e", "Neotree focuse<CR>")
vim.keymap.set("n", "<leader>ff", ":Telescope find_files<CR>")
vim.keymap.set("n", "<leader>th", ":Telescope colorscheme<CR>")
vim.keymap.set("n", "<leader>ft", vim.lsp.buf.format, {})
